"""
389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s
and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
"""

# Solution

class Solution(object):
    def findTheDifference(self, s, t):
        s, t = sorted(s), sorted(t)
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]
        return t[-1]